package com.workq.testpoc;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class SSNVerificationData implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public SSNVerificationData() {
    }




}